### ISSUE TITLE
how to close connected

### ISSUE THREAD

**Issue by DragonQuestHero** [SqliteModernCpp/sqlite_modern_cpp#141]
`*_DB = new database(File_Name);`
Except `delete _DB `
Any other method to close database connect?
thanks

**Comment by zauguin** [comment]
You can use a local variable, then the connection is closed when it goes out of scope:

    {
      sqlite::database db(filename);
      db << "...";
      // more commands
    }
    // The connection ran out of scope, so it will be closed.

This is the RAII way of doing it and it will also automatically close the connection when an exception occurs.
If you want to close a connection without destroying the `database` object, you can move a away from it:

    sqlite::database db(filename);
    ...;
    (void)[v=std::move(db)]{};
    // database closed

or


    sqlite::database db(filename);
    ...;
    {auto v=std::move(db);}
    // database closed

**Comment by DragonQuestHero** [comment]
OK! thank you @zauguin
