### ISSUE TITLE
Test failures are ignored

### ISSUE THREAD

**Issue by zauguin** [SqliteModernCpp/sqlite_modern_cpp#146]
Running `ctest .` or `cmake --build --target test .` always succeeds, even if the test
```c++
#include <catch.hpp>

TEST_CASE("This is supposed to fail", "[pleasefailme]") {
  REQUIRE(false);
}
```
is added.

Running `./tests` directly results in the expected failure for failing tests.

**Comment by aminroosta** [comment]
Thanks, @zauguin.
I expected `ctest` to return when a test fails however it's clearly not the case.

 will you send a PR or should I?
