### ISSUE TITLE
Not building on VS 2017, issues in utf16_utf8.h

### ISSUE THREAD

**Issue by mtissington** [SqliteModernCpp/sqlite_modern_cpp#150]
I can no longer build ... using codecvt breaks the build.

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2589	'(': illegal token on right side of '::'	ActiveWords DLL	c:\activewords4\activewords dll\sqlite_modern_cpp\utility\utf16_utf8.h	14	
Error	C2143	syntax error: missing ')' before '.'	ActiveWords DLL	c:\activewords4\activewords dll\sqlite_modern_cpp\utility\utf16_utf8.h	14	
Error	C3928	'->': trailing return type is not allowed after a parenthesized declarator	ActiveWords DLL	c:\activewords4\activewords dll\sqlite_modern_cpp\utility\utf16_utf8.h	14	
Error	C3484	syntax error: expected '->' before the return type	ActiveWords DLL	c:\activewords4\activewords dll\sqlite_modern_cpp\utility\utf16_utf8.h	14	
Error	C3613	missing return type after '->' ('int' assumed)	ActiveWords DLL	c:\activewords4\activewords dll\sqlite_modern_cpp\utility\utf16_utf8.h	14	
Error	C2146	syntax error: missing ')' before identifier 'size'	ActiveWords DLL	c:\activewords4\activewords dll\sqlite_modern_cpp\utility\utf16_utf8.h	14	
Error	C3646	'size': unknown override specifier	ActiveWords DLL	c:\activewords4\activewords dll\sqlite_modern_cpp\utility\utf16_utf8.h	14	

and it keeps going ...

**Comment by zauguin** [comment]
@mtissington Are you including `windows.h` before include sqlite_modern_cpp?

**Comment by zauguin** [comment]
This might be related to `max` being defined as a macro.
Please test if you still get the error with https://github.com/zauguin/sqlite_modern_cpp/commit/135db903f719c9cf92638a669f8cc9f29831447e

**Comment by mtissington** [comment]
great - fixed with `max` - thanks!
