### ISSUE TITLE
latest build - error: Invalid UTF-16 input

### ISSUE THREAD

**Issue by mtissington** [SqliteModernCpp/sqlite_modern_cpp#151]
The latest build is now causing the error error: Invalid UTF-16 input.
This works with prior builds ...

I am opening an existing UTF-16 database.

And this is the code that is causing the error, all inputs are std::u16string

		*awdb_ << u"SELECT value FROM settings WHERE setting = ? AND ((roaming = 0 AND machine_guid = ?) OR (roaming = 1))"
			<< setting << machine_guid_
			>> value;

**Comment by zauguin** [comment]
I can't reproduce this issue.
@mtissington  Can you try running the following program:

```c++
#include <iostream>
#include <sqlite_modern_cpp/utility/utf16_utf8.h>

int main(int argc, char **argv) try {
  sqlite::utility::utf16_to_utf8(
      u"SELECT value FROM settings WHERE setting = ? AND ((roaming = 0 AND "
      u"machine_guid = ?) OR (roaming = 1))");
} catch(const std::exception &ex) {
  std::cerr << ex.what() << '\n';
  return -1;
}
```

**Comment by mtissington** [comment]
I'm not sure what you mean, run this program - it doesn't reference a database.

**Comment by aminroosta** [comment]
@mtissington we use `sqlite::utility::utf16_to_utf8` to convert between the two, The error message `Invalid UTF-16 input` is probably from that function. Could you please confirm using the code snippet from zauguin.

**Comment by mtissington** [comment]
With the above code I get the same error.

**Comment by zauguin** [comment]
@mtissington Thanks. Can you try the same code with the changes in 1ffa5b8a430b5ed87f3736dce6ddaeee4bda255a?
This could print a different error message.

**Comment by mtissington** [comment]
I needed to fix the error in the above - change error:: to errors:: then when I run a get the same error still.
