### ISSUE TITLE
compilation error in error_codes.h with MSVC

### ISSUE THREAD

**Issue by hwelzel** [SqliteModernCpp/sqlite_modern_cpp#179]
This simple code fails compilation on Visual Studio (fyi I used 15.7.6) and sqlite 3.8. Works on gcc and clang.

#include <sqlite_modern_cpp/errors.h>
int main() {
	return 0;
}

I get a bunch of errors such as:
1>    sqlite_modern_cpp\lists\error_codes.h(50): error C2121: '#': invalid character: possibly the result of a macro expansion
1>    sqlite_modern_cpp\lists\error_codes.h(17): error C2059: syntax error: 'if'
1>    sqlite_modern_cpp\lists\error_codes(17): error C2059: syntax error: 'public'
1>    sqlite_modern_cpp\lists\error_codes.h(50): error C2143: syntax error: missing ';' before '{'
1>    sqlite_modern_cpp\lists\error_codes.h(50): error C2447: '{': missing function header (old-style formal list?)
1>    sqlite_modern_cpp\lists\error_codes.h(17): error C2143: syntax error: missing ';' before 'if'
1>    sqlite_modern_cpp\lists\error_codes.h(50): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>    sqlite_modern_cpp\lists\error_codes.h(51): error C2143: syntax error: missing ';' before '<class-head>'
1>    sqlite_modern_cpp\lists\error_codes.h(53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>    sqlite_modern_cpp\lists\error_codes.h(85): error C2121: '#': invalid character: possibly the result of a macro expansion

I tracked down the reason as the following lines in error_codes.h which happen inside a macro.
#if SQLITE_VERSION_NUMBER >= 3009000

Locally I have remove the version checks from inside the macro and it works. For example
This:
SQLITE_MODERN_CPP_ERROR_CODE(AUTH,auth,
#if SQLITE_VERSION_NUMBER >= 3009000
  SQLITE_MODERN_CPP_ERROR_CODE_EXTENDED(AUTH,USER,auth,user)
#endif
)
Becomes:
SQLITE_MODERN_CPP_ERROR_CODE(AUTH,auth,)
#if SQLITE_VERSION_NUMBER >= 3009000
  SQLITE_MODERN_CPP_ERROR_CODE_EXTENDED(AUTH,USER,auth,user)
#endif

Apparently it is illegal to use #if inside macros. https://stackoverflow.com/questions/19111383/ifdef-inside-a-macro-call-works-with-gcc-but-not-with-msvc
But gcc's implementation seems to allows it.

**Comment by aminroosta** [comment]
here is a PR to dev branch https://github.com/SqliteModernCpp/sqlite_modern_cpp/pull/180

@hwelzel you nailed the issue, 
the solution is to move the `#if` condition out of the macro expansion.

However i don't have a windows machine to check that PR.
I'd appreciate if you could help check it on visual studio 🙏

**Comment by aminroosta** [comment]
@hwelzel where you able to check this fix?

**Comment by hwelzel** [comment]
Sorry @aminroosta I missed your previous message. Thanks for looking into it. I should have checked the dev branch. My original description was based on the 3.2 release. I see dev changed a bit already.

I also only have access to Windows/Visual Studio at work. Will test it on Monday and come back to you. Thanks!

**Comment by hwelzel** [comment]
Hi @aminroosta, I can compile your branch fine without problems using MSVC 19.14.26433.0! Thanks.

Well, there is just one thing compared to the 3.2 release. I now get this extra warning, which I turn into error. I had to disable it around the sqlite_modern_cpp/sqlite_modern_cpp.h include. Not a big deal for me, but thought I'd let let you know in case you want to fix it.

11>    sqlite_modern_cpp\type_wrapper.h(132): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
11>    sqlite_modern_cpp\type_wrapper.h(136): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data

**Comment by aminroosta** [comment]
@hwelzel Thanks a lot.

The PR is now merged,
I will fix the "conversion from 'double' to 'float'" warning in another PR.
