### ISSUE TITLE
aggregate functions with multiple parameters

### ISSUE THREAD

**Issue by BrannonKing** [SqliteModernCpp/sqlite_modern_cpp#186]
I wanted to write an aggregate function that took in a second parameter. In my situation the second parameter was a string literal (not a column). This would be similar to the built-in GROUP_CONCAT function. Is it possible to support this? I couldn't get it to compile. Alternately, I'll just redifine the function before calling it and pass my parameter in through the lambda closure -- in which case it might be nice if there was an "undefine" method available.

**Comment by zauguin** [comment]
It doesn't really make a difference if the second parameter is constant or a column, SQLite will treat a literal exactly as if there is a column which has the same value in every row.

Anyway, the following example of a aggregate function with two parameters works for me: 
```c++
#include <optional>
#include <iostream>
#include <string>
#include <sqlite_modern_cpp.h>

int main(int argc, char const* argv[])
{
  sqlite::database db("testdb");
  db.define("my_concat", [](std::optional<std::string> &ctxt, std::string entry, std::string delim) {
    if(ctxt) {
      *ctxt += delim + entry;
    } else {
      ctxt = entry;
    }
  }, [](std::optional<std::string> &ctxt) {
    return ctxt.value_or("");
  });
  std::string result;
  db << "SELECT my_concat(name, ' + ') FROM nodes;" >> result;
  std::cout << result;
  return 0;
}
```

**Comment by BrannonKing** [comment]
Thanks. So it looks like the third parameter cannot be passed to the final function directly. That's okay. I can stick into my aggregating type and pull it out for use in the final function. This example should make it into your documentation at some point (and maybe change it to use stringstream).
