### ISSUE TITLE
unique_ptr receiving single or absent result

### ISSUE THREAD

**Issue by BrannonKing** [SqliteModernCpp/sqlite_modern_cpp#188]
From the documentation, I had expected this code to work:
```
std::unique_ptr<TData> root;
_db << "SELECT data FROM claims WHERE name = '' LIMIT 1" >> root;
ret.emplace_back(parentKey, root ? *root : -1);
```
However, when there is no matching rows I get an exception about a missing row in the code that tries to set root. What is the preferred way to handle this?

**Comment by zauguin** [comment]
The `std::unique_ptr` would be unset, iff `claims` does contain a row, but this row has `NULL` in the `data` column. Using `>> var` for some (non function) variable `var` always assumes that there is exactly one row.
Do you have a suggestion how this can be made more clear in the README?

Instead, you could e.g. use a lambda:

```
bool found = false;
_db << "SELECT data FROM claims WHERE name = '' LIMIT 1" >> [&] (TData root) {
  found = true;
  ret.emplace_back(parentKey, root);
};
if (!found)
  ret.emplace_back(parentKey, -1);
```

**Comment by BrannonKing** [comment]
I ended up doing something like what you suggested there. It is quite verbose, though. 

I think I would like something like what I suggested to work for std::optional as well. Is it possible to detect whether or not the callback in `_extract_single_value` can take a null? If so, you could just pass a null in there when there are no rows instead of throwing an exception.

I was wondering if this approach might be faster: "SELECT IFNULL(MAX(data), -1) FROM claims WHERE name = ''".

For the README, we could add something to the "NULLs" section like "This use of unique_ptr applies to missing/null fields but not to missing/null rows."

**Comment by zauguin** [comment]
A user could try to read multiple columns and we would have to check all of them to know if all accept NULL. This could be worked around by throwing the exception when the first column not supporting NULL is detected, but that's a bit beside the point:

The interface would be just weird, it mixes up two completely different cases by handling `NULL` and a completely missing row in the same way. In many circumstances, an existing row containing an explicit NULL in one column has a different meaning than a row missing entirely.

> For the README, we could add something to the "NULLs" section like "This use of unique_ptr applies to missing/null fields but not to missing/null rows."

The point is that fields containing NULL still exists, they just don't have a value. I wouldn't understand what a "missing field" in SQL would be. On the other hand, rows might be missing, but that doesn't make them NULL rows: I would understand a SQL NULL row to be a row containing (only?) NULLs.

Also, another way to solve you original problem would be using the iterator interface:
```
auto expr = _db << "SELECT data FROM claims WHERE name = '' LIMIT 1";
auto iter = expr.begin();
TData root = -1;
if (iter != expr.end()) *iter >> root;
ret.emplace_back(parentKey, root);
```
That isn't much shorter, but I think it shows what's going on and if you use prepared statements anyway it looks quite nice.
