### ISSUE TITLE
Sql Logic Error

### ISSUE THREAD

**Issue by Hirobreak** [SqliteModernCpp/sqlite_modern_cpp#195]
I'm having trouble opening an unencrypted sqlite database with sqlcipher. I recently integrated sqlcipher and for my app's purpose I need to read and write some data before encrypting the database.

I successfully compiled sqlcipher as follows:
```
../configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="/usr/lib/x86_64-linux-gnu/libcrypto.a"
```

And I'm initializing my database as follows:

```
sqlcipher_config config;
config.flags = OpenFlags::FULLMUTEX | OpenFlags::SHAREDCACHE | OpenFlags::READWRITE;
sqlcipher_database db(dbPath, config);
```

But when I try to initialize it I get the following error: SQL logic error

I'm using node-gyp to compile my executable and I'm stating libraries as follows:

```
"libraries": [
  "-pthread",
  "-ldl",
  "/usr/lib/x86_64-linux-gnu/libssl.a",
  "/usr/lib/x86_64-linux-gnu/libcrypto.a",
  "/usr/local/lib/libsqlcipher.a",
  "/usr/local/lib/libsignal-protocol-c.a",
  "/usr/lib/libcivetweb.so",
  "/usr/local/lib/libcjson.a",
  "/usr/local/lib/spdlog/libspdlog.a"
]
```
I'm running Ubuntu and libssl 1.1.0
Any help will be much appreciated

**Comment by zauguin** [comment]
I don't really understand what you are trying to do:

> I'm having trouble opening an unencrypted sqlite database with sqlcipher.
If you want to open an unencrypted database you can just ignore that you are even using sqlcipher and open it with `sqlite::database`. `sqlite_database` is only for encrypted databases.

> I recently integrated sqlcipher and for my app's purpose I need to read and write some data before encrypting the database.

I don't understand what you mean here, but if you try to encrypt an existing database: That is not supported by sqlcipher. You basically have to copy your existing, unencrypted, database into a new, encrypted, database file. `sqlite_modern_cpp` does not provide a interface to help you with this, so you would have to do this manually.

You can read and write into a separate, unencrypted, database file at any time of course.

**Comment by Hirobreak** [comment]
I thought sqlite_database also supported unencrypted databases so I wouldn't need an interface for unencrypted dbs and a second interface for encrypted dbs.
Thank you for your reply I'll try that but that should be the solution to my problem.

**Comment by zauguin** [comment]
@Hirobreak You don't really need separate interfaces because sqlcipher_database inherits from database, so you can use functions which espect a (reference to a) unencrypted database also for encrypted databases.
