### ISSUE TITLE
support for user definer type in getting values

### ISSUE THREAD

**Issue by marciso** [SqliteModernCpp/sqlite_modern_cpp#197]
Hi,

I have noticed that with a little extension, the library could support getting any user defined type. (In my case I wanted to get one of my columns as `std::array<char, N>`, not `std::string` -- to avoid some dynamic allocations). This could be quite handy with working with blobs that can be represented by user classes. 

AFAICT, the necessary change is to provide a user-defined `get_col_from_db` for the custom type (and maybe `get_val_from_db`, and maybe other: `store_result_in_db`, `operator<<`, depending on needs..), inside `sqlite` namespace.

Unfortunately, `get_col_from_db` wants to access `database_binder::_stmt`, which is private. (Simply making it not-private, would have worked for me). I chose to add the `_stmt` accessor (`auto & stmt() const { return _stmt; }` ) to break the encapsulation. Alternatively, I don't see a reason why `get_col_from_db` couldn't take `sqlite3_stmt*` instead of `database_binder & ` as the parameter, which might be a nicer API for extensions. 

Could you consider adding `database_binder::stmt()` or changing `get_col_from_db` signature?

For reference, with my accessor I only needed this:

```
namespace sqlite {
template<std::size_t N>
    inline void get_col_from_db(database_binder& db, int inx, std::array<char, N> & s) {
		if(sqlite3_column_type(db.stmt().get(), inx) == SQLITE_NULL) {
			s[0] = '\0';
		} else {
			std::strncpy(s.data(), reinterpret_cast<char const *>(sqlite3_column_text(db.stmt().get(), inx)), N);
    }
}
}
```

**Comment by marciso** [comment]
Going forward, I have removed `private:` from the `database_binder`. This allowed me to customise the behaviour to my needs. For example different implementation of the callbacks.

**Comment by zauguin** [comment]
@marciso Did you see the `dev` branch? There, type support is separated from the rest of the library in `sqlite_modern_cpp/type_wrapper.h` and no longer takes a `database_binder` but a `sqlite3_stmt*`. Does that work for you?

**Comment by marciso** [comment]
Thanks! I think this solves my original problem!

**Comment by marciso** [comment]
Meantime I came up with a different solution to solve my problem ;)

The interface is rubbish (passing tuple with 3 or 5 args changes the meaning), but it was quickiest/dirties what I could come up with.

The idea here was to add extra callbacks before/after reading the table and before/after reading the row that could do some initialisation. For example: I call "SELECT * FROM T", I expect column "key" in the result, but not sure where it is (first, second, ...), also number of column and column names may change to some extend (opening slightly different DB that evolved over time). So, I discover the primary key and remember column names before reading the result; the callback before reading the row pre-allocates necessary space that will be filled in on subsequent callbacks.

```
class dynamic_binder
{
    template <typename Function, std::size_t Index> using nth_argument_type =
        typename utility::function_traits< Function >::template argument<Index>;

 public:
    template<typename T, typename ...Args> static void call(T && t, Args &&... args) { std::forward<T>(t)(std::forward<Args>(args)...); }
    template<typename ...Args> static void call(std::nullptr_t, Args &&... args) { }

    template<typename Function1, typename Function2, typename Function3>
        static void run(database_binder& db, int n, Function1&& start, Function2&& column, Function3&& end)
        {
            int i = 0;
            call(start, i, n);
            for (; i < n; ++i)
            {
                typename std::remove_cv<typename std::remove_reference<nth_argument_type<Function2, 0>>::type>::type value{};
                get_col_from_db(db, i, value);
                call(column, std::move(value), i);
            }
            call(end, i, n);
        }

    static void _extract(database_binder & db, std::function<void(int &)> call_back,
            std::function<void(database_binder &, int &)> start, std::function<void(int &)> end)
    {
        db._start_execute();

        int n = sqlite3_column_count(db._stmt.get());

        start(db, n);

        int hresult;
        while ((hresult = sqlite3_step(db._stmt.get())) == SQLITE_ROW) {
            call_back(n);
        }

        end(hresult);

        if (hresult != SQLITE_DONE) {
            errors::throw_sqlite_error(hresult, db.sql());
        }
    }
};

template <typename Function1, typename Function2, typename Function3, typename Function4, typename Function5>
void operator >(database_binder && db, std::tuple<Function1, Function2, Function3, Function4, Function5> && funcs)
{
    dynamic_binder::_extract(db,
            [&funcs, &db](int & n) {
                dynamic_binder::run(db, n, std::get<1>(funcs), std::get<2>(funcs), std::get<3>(funcs));
            },
            [&funcs](database_binder & db, int & n) {
                dynamic_binder::call(std::forward<decltype(std::get<0>(funcs))>(std::get<0>(funcs)), db, n);
            },
            [&funcs](int & res) {
                dynamic_binder::call(std::forward<decltype(std::get<4>(funcs))>(std::get<4>(funcs)), res);
            });
}
template <typename Function1, typename Function2, typename Function3>
void operator >(database_binder && db, std::tuple<Function1, Function2, Function3> && funcs)
{
    dynamic_binder::_extract(db,
            [&funcs, &db](int & n) {
                dynamic_binder::run(db, n, std::get<0>(funcs), std::get<1>(funcs), std::get<2>(funcs));
            },
            [](auto &, int &){}, [](int &){});
}
template <typename Function>
void operator >(database_binder && db, Function&& func)
{
    dynamic_binder::_extract(db,
            [&func, &db](int & n) { dynamic_binder::run(db, n, nullptr, func, nullptr); },
            [](auto &, int &){}, [](int &){});
}
```

Sample code:

```
int key_idx = -1;
std::map<key_value, std::vector<std::variant<...>>> per_key;
decltype(per_key)::iterator current_line;

db << "SELECT * FROM T" > std::make_tupe(
  // open table:
  [&](auto & db, int columns) { for ( int = 0; i < columns; ++i ) column_names.push_back(sqlite3_column_name(stmt, i)));
    key_idx = find_key(column_names); },
  // open row 
  [&](int & start_from, int cols) { current_line = per_key.insert(sqlite3_column_int64(key_idx), {}).first; },
  // read cell / next value
  [&](variant && v, int col_num) { current_line->second->push_back(...); /* column_names[col] */  },
  nullptr, nullptr // no-post-hooks
);
// brrr... 
```
