### ISSUE TITLE
std::optional and std::variant not supported with MSVC 2019

### ISSUE THREAD

**Issue by marciso** [SqliteModernCpp/sqlite_modern_cpp#199]
Unfortunately, MSVS does updates `__cplusplus` value by default: you need to add `/Zc:__cplusplus` to the compiler (https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/).  Which means the library will not add support to `#include<optional>` and `#include<variant>` even though the files are available in MSVC (and conformant to the standard, at lest to the extend I cared about), and I use them.

I would suggest the following patch:

```
--- a/3rdparty/single-files/sqlite_modern_cpp.h
+++ b/3rdparty/single-files/sqlite_modern_cpp.h
@@ -12,7 +12,7 @@
 #define MODERN_SQLITE_VERSION 3002008
 
 #ifdef __has_include
-#if __cplusplus > 201402 && __has_include(<optional>)
+#if __has_include(<optional>)
 #define MODERN_SQLITE_STD_OPTIONAL_SUPPORT
 #elif __has_include(<experimental/optional>)
 #define MODERN_SQLITE_EXPERIMENTAL_OPTIONAL_SUPPORT
@@ -20,7 +20,7 @@
 #endif
 
 #ifdef __has_include
-#if __cplusplus > 201402 && __has_include(<variant>)
+#if __has_include(<variant>)
 #define MODERN_SQLITE_STD_VARIANT_SUPPORT
 #endif
 #endif
```

**Comment by zauguin** [comment]
This breaks compiling with older standards on other compilers. (Often the file is always available, but if it is included with older `__cplusplus` version is just throws a compile error.)

**Comment by marciso** [comment]
Fair enough.
How about ignoring `__cplusplus` in MSVC and relay on `_MSVC_LANG` (e.g. https://stackoverflow.com/questions/43639122/which-values-can-msvc-lang-have 
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019)

**Comment by marciso** [comment]
https://github.com/SqliteModernCpp/sqlite_modern_cpp/pull/202

**Comment by aminroosta** [comment]
I merged the PR - seemed OK to me.

please reopen if any issue.
