### ISSUE TITLE
Does this library support the JSON1 extension?

### ISSUE THREAD

**Issue by remz1337** [SqliteModernCpp/sqlite_modern_cpp#208]
Hello,

I would like to store JSON objects in sqlite. Does this library support the JSON1 extension?

Thanks

**Comment by aminroosta** [comment]
No we do not explicitly support extensions.
However skimming through the [docs for json1](https://www.sqlite.org/json1.html) It seems to add a few application-defined and table-valued functions.

You can give it a try, My hunch is that it will just work.

load json1 with
```
int sqlite3_load_extension(
  sqlite3 *db,          /* Load the extension into this database connection */
  const char *zFile,    /* Name of the shared library containing extension */
  const char *zProc,    /* Entry point.  Derived from zFile if 0 */
  char **pzErrMsg       /* Put error message here if not 0 */
);
```

You can get the `sqlite3 *db` from this library's [.connection()](https://github.com/SqliteModernCpp/sqlite_modern_cpp/blob/master/hdr/sqlite_modern_cpp.h#L446) method. it returns a `std::uniqe_ptr<sqlite3>` and is the recommended way to hook into sqlite internals.
