### ISSUE TITLE
I dont know how to compile my C++ files with this library

### ISSUE THREAD

**Issue by beemibrahim** [SqliteModernCpp/sqlite_modern_cpp#213]
What are the linker options to compile with your library

**Comment by zauguin** [comment]
It's a header only library, so it doesn't need any linker options. Just add the `hdr` directory to you compilers header include path and the library should work.

**Comment by fawdlstty** [comment]
install vcpkg and run:
`vcpkg install sqlite-modern-cpp:x86-windows-static`
after install, use `#include <sqlite_modern_cpp.h>`, I can compile.
