### ISSUE TITLE
Project does not work in VS2022

### ISSUE THREAD

**Issue by MichaelFinance** [SqliteModernCpp/sqlite_modern_cpp#227]
I added 
../hdr/ path into C++ project properties: C++->General->Additional Include Directories.

It did not work.

how can I solve this problem?

**Comment by aminroosta** [comment]
Google it.

**Comment by flaviu22** [comment]
> I added ../hdr/ path into C++ project properties: C++->General->Additional Include Directories.
> 
> It did not work.
> 
> how can I solve this problem?

Did you solve the issue?
